import { Inter } from 'next/font/google'
import './globals.css'

// Custom Componenets
import NavBar from './components/Navbar'
import Footer from './components/Footer'

// Custom Function
import { useCreateServerClient } from './api/customHooks'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Van Life',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const supabase = await useCreateServerClient();
  const { data } = await supabase.auth.getSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar user={data.session?.user}/>
          {children}
        <Footer />
      </body>
    </html>
  )
}
