import Link from "next/link"

// Custom Functions
import { getVan } from "@/app/api/vanFetching";

// Custom Components
import TypeTag from "@/app/components/TypeTag";
import HostVanDetailNav from "./HostVanDetailNav"

export const metadata = {
  title: 'Van Life',
  description: 'Generated by create next app',
}

export default async function HostVanDetailLayout({ children, params }) {
  const van = await getVan(params.id)

  return (
    <div>
      <Link href="/host/vans" className="host-van--detail__back">← Back to all vans</Link>
      <div className="host-van--detail">
          <div className='host-van--detail__top-container'>
              <img className="host-van--detail__image" src={ van.imageUrl } alt="An image of a van available for rental." />
              <h1 className="host-van--detail__name">{ van.name }</h1>
              <h3 className="host-van--detail__price">${ van.price }<span className="host-van--detail__price-subtext">/day</span></h3>
              <TypeTag type={ van.type } className="host-van--detail__type"/>
          </div>
          <HostVanDetailNav id={van.id}/>
          {children}
      </div>
    </div>
  )
}
