import HostNav from "./HostNav"
import { redirect } from 'next/navigation'

// Custom Hooks
import { myCreateServerClient } from "../api/customHooks"

export const metadata = {
  title: 'Van Life',
  description: 'Generated by create next app',
}

export default async function HostLayout({ children }) {
    const supabase = await myCreateServerClient();
    const { data } = await supabase.auth.getSession();
    
    if(!data.session){
        redirect('/login')
    }

    return (
    <div className="host">
        <HostNav />
        {children}
    </div>
    )
}
